services:
  db:
    container_name: db
    image: postgres:alpine
    ports:
      - '5432:5432'
    volumes:
      - ./db_data/:/var/lib/postgresql/data/
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
